//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenP10.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTE()
        {
            this.REPORTE = new HashSet<REPORTE>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Empresa { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public int Donacion { get; set; }
        [Display(Name = "PIB %")]
        public int Pib { get; set; }
        [Display(Name = "Pais, Ciudad")]
        public int Ubicacion { get; set; }
        public int Producto { get; set; }

        [Display(Name = "PIB %")]
        public virtual PIB PIB1 { get; set; }
        [Display(Name = "Producto Beneficio")]
        public virtual PRODUCTO PRODUCTO1 { get; set; }
        [Display(Name = "Pais, Ciudad")]
        public virtual UBICACION UBICACION1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REPORTE> REPORTE { get; set; }
    }
}
