//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenP10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTE
    {
        public int Id { get; set; }
        public int Cliente { get; set; }
        public int IVA { get; set; }
        public int ISR { get; set; }
        public int AHORRO { get; set; }
        public Nullable<int> MESES { get; set; }
        public int TOTAL { get; set; }
        public int Servicio { get; set; }
    
        public virtual CLIENTE CLIENTE1 { get; set; }
        public virtual SERVICIO SERVICIO1 { get; set; }
    }
}
